### ISSUE TITLE
[FEAT] : change header card descpription

### ISSUE THREAD

**Issue by osbc2022** [osbc2022/watch-product-landing-page#11]
### ✏️ Description

To do :- 
- [ ] write proper description in the header card

> Note :- make sure you check the Contribution Guideline, you can find it in the readme Section

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/115569958/196034775-79f1036d-aeb1-4eab-bc95-2967b645200e.png)

**Comment by amitanshusahu** [comment]
i would like to work on this
