### ISSUE TITLE
[FEAT] : add Copyrights in the footer section

### ISSUE THREAD

**Issue by osbc2022** [osbc2022/watch-product-landing-page#12]
### ✏️ Description

To do :- 
- [ ] write copyright in the footer section 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/115569958/196035370-8769c746-8bcf-4ed2-9f8e-c3f6f2099a72.png)

**Comment by Maryam-Momoh** [comment]
can i be assigned to this task?

**Comment by osbc2022** [comment]
@Maryam-Momoh  , go ahead :star_struck:

**Comment by Maryam-Momoh** [comment]
![Appla Watches - Google Chrome 10_17_2022 8_15_39 PM (2)](https://user-images.githubusercontent.com/75956011/196292825-ca5f2399-785e-4cca-966f-004f8cac389e.png)

take a look

**Comment by osbc2022** [comment]
@Maryam-Momoh , looks great

**Comment by osbc2022** [comment]
make a PR
