### ISSUE TITLE
[FEAT] : Add Conribution Section in README.md

### ISSUE THREAD

**Issue by osbc2022** [osbc2022/watch-product-landing-page#16]
### ✏️ Description

To do:
- [ ] use the github api
- [ ] list all the contribution in the readme below this section :point_down: 
![image](https://user-images.githubusercontent.com/115569958/196049523-14af2e3d-8e10-4744-9bc7-f6559048e991.png)

> Note: make sure you check the Contribution Guidline

**Comment by amitanshusahu** [comment]
i would like to work on this

**Comment by osbc2022** [comment]
Great !! , go for it :heart_eyes:
