### ISSUE TITLE
[FEAT] : making nav bar responsive

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/watch-product-landing-page#20]
### ✏️ Description

the nav bar is not responsive , it breaks when width goes below 756px 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/83657737/196086202-5a9b63b3-57e4-475f-ac49-1c7f958fdd8d.png)

**Comment by osbc2022** [comment]
Good :star_struck: @amitanshusahu  go for it
