### ISSUE TITLE
[BUG] : social links in footer 

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/watch-product-landing-page#21]
### ✏️ Describe the bug

the social links in the footer can be converted into icons

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/83657737/196150288-f08cf6d7-b164-4e1a-a7ec-8ca5ef0bc93b.png)

**Comment by amitanshusahu** [comment]
i would like to work on this 😄

**Comment by osbc2022** [comment]
ok go on :heart_eyes: 

> NOTE:- the images should be white and should match the looks of the website
