### ISSUE TITLE
[BUG] : footer is not responsive 

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/watch-product-landing-page#22]
### ✏️ Describe the bug

the footer overflows for width less than 700px 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/83657737/196151929-f82d4726-2834-4ff5-83ee-51e0a1b98de3.png)

**Comment by amitanshusahu** [comment]
i can work on this 😄

**Comment by osbc2022** [comment]
ya :smile:  go for it
