### ISSUE TITLE
[DOCS] : documentation on PR in contribution.md is not properly explained

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/watch-product-landing-page#8]
### ✏️ Description

To do: 
- [ ] adding images in the PR section
- [ ] making the language more easy to understand

**Comment by osbc2022** [comment]
Ok go for it :star_struck:

**Comment by starohit** [comment]
assign me

**Comment by osbc2022** [comment]
@starohit  , this issue has already been assigned and fixed you could make a new issue
