### ISSUE TITLE
[FEAT] :responsive

### ISSUE THREAD

**Issue by abhijeet78880** [osbc2022/watch-product-landing-page#9]
### ✏️ Description

responsive for mobile device

### 📸 Screenshots

![Screenshot from 2022-10-16 13-23-03](https://user-images.githubusercontent.com/84617107/196024602-1ebff7c5-ee56-4b09-94ae-e0bb4ba25959.png)

**Comment by osbc2022** [comment]
Awesome :star_struck: , go for it @abhijeet78880
